kind: Service
apiVersion: "v1"
metadata:
  namespace: kubetree
  name: backend
  labels:
    app: kubetree
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
  selector:
    app: kubetree
