apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kubetree
  name: kubetree
  labels:
    app: kubetree
spec:
  replicas: 1
  template:
    metadata:
      name: kubetree
      labels:
        app: kubetree
    spec:
      containers:
        - name: backend
          image: giantswarm/kubetree-backend
          ports:
            - containerPort: 5000
              name: backend-http
        - name: frontend
          image: giantswarm/kubetree-frontend
          ports:
            - containerPort: 80
              name: frontend-http
