kind: Service
apiVersion: "v1"
metadata:
  namespace: kubetree
  name: kubetree
  labels:
    app: kubetree
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: frontend-http
  selector:
    app: kubetree
